apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app4
  namespace: argocd
spec:
  destination:
    namespace: helm-app4
    server: https://kubernetes.default.svc
  project: dev-project-4
  sources:
    - chart: helm-chart-test
      repoURL: 'https://vikaslall.github.io/helm-chart/'
      targetRevision: 0.1.2
      helm:
        valueFiles:
          - $values/apps-helm-chart/prod/app4/values.yaml
    - repoURL: 'git@github.com:VikasLall/argocdappofapps.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
