apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-app-helm-approach-generators-qa
  namespace: argocd
spec:
  generators:
  - git:
      directories:
      - path: apps-helm-chart/qa/*
      repoURL: git@github.com:VikasLall/argocdappofapps.git
      revision: main
  template:
    metadata: 
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      destination:
        namespace: '{{path.basename}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{path}}'
        repoURL: git@github.com:VikasLall/argocdappofapps.git
        targetRevision: main
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
        syncOptions:
        - allowEmpty=true
        - CreateNamespace=true

