apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qa-namespace-config
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/VikasLall/argocdappofapps.git
      revision: main
      directories:
      - path: apps-helm-chart/qa/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/VikasLall/argocdappofapps.git
        targetRevision: main
        path: apps-helm-chart/namespace-config
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
