apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app6
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-app6
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: helm-chart-test
      repoURL: 'https://vikaslall.github.io/helm-chart/'
      targetRevision: 0.1.1
      helm:
        valueFiles:
          - $values/apps-helm-chart/dev/app6/values.yaml
    - repoURL: 'git@github.com:VikasLall/argocdappofapps.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
