apiVersion: batch/v1
kind: Job
metadata:
  name: drupal-deploy-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      containers:
        - name: example-container
          image: ubuntu
          command: ["echo", "Hello World"]
      restartPolicy: Never
