apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "GET"
          - "curl -v -X GET 'https://postsync.free.beeceptor.com' -H 'some-header: some-value'"
      restartPolicy: Never
  backoffLimit: 2
