apiVersion: batch/v1
kind: Job
metadata:
  name: alpine-git-shell-command-job
spec:
  template:
    spec:
      containers:
      - name: alpine-git-container
        image: alpine/git
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Running a shell command inside alpine/git container";
          # Add your shell commands here
          # For example, cloning a repository
          git config --global user.name "VikasLall"
          echo "Username set "
          git clone https://github.com/VikasLall/argocdappofapps.git;
          ls
          echo "Repository cloned";
      restartPolicy: Never