apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
      - name: example-container
        image: alpine/git
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Hello, World!"
      restartPolicy: Never