apiVersion: batch/v1
kind: Job
metadata:
  namespace: helm-app1
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "99"

spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "GET"
          - "https://postsync.free.beeceptor.com"
      restartPolicy: Never
  backoffLimit: 2