apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-app2
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - chart: helm-chart
      repoURL: 'https://vikaslall.github.io/helm-chart/'
      targetRevision: 0.1.1
      helm:
        valueFiles:
          - $values/apps-helm-chart/apps/app2/values.yaml
    - repoURL: 'https://github.com/VikasLall/argocdappofapps.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true

