# Create External Secrets config file
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets-config
  namespace: external-secrets

spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cred-dbcreator
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: app1-db-external-secrets