apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app3
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "99"
spec:
  destination:
    namespace: helm-app3
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: helm-chart-test
      repoURL: 'https://vikaslall.github.io/helm-chart/'
      targetRevision: 0.1.2
      helm:
        valueFiles:
          - $values/apps-helm-chart/prod/app3/values.yaml
    - repoURL: 'git@github.com:VikasLall/argocdappofapps.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
