apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: '{{.path.basename}}'
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  limits:
  - default:
      cpu: 2
      memory: 512Mi
    defaultRequest:
      cpu: 2
      memory: 256Mi
    type: Container
